[package]
name = "tracer"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.29.0", features = ["ptrace"] }
procfs = { version = "0.17.0", default-features = false, features = [] }
rand = "0.8.5"
xxhash-rust = { version = "0.8.12", features = ["xxh3"] }
